name: camino-suite ci

on:
  workflow_dispatch:
  push:    
    branches:
      - main
      - dev
  pull_request:
    branches:
        - main
        - dev

env:
  node_version: 16

jobs:
  BuildAndDeploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      with: submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
          
      - name: install yarn dependencies - host
        working-directory: ./host
        run: yarn install
      - name: build - host
        working-directory: ./host
        run: yarn build
      - name: install yarn dependencies - explorer
        working-directory: ./blockexplorer
        run: yarn install
      - name: build - explorer
        working-directory: ./blockexplorer
        run: yarn build
      - name: install yarn dependencies - wallet
        working-directory: ./wallet
        run: yarn install
      - name: build - wallet
        working-directory: ./wallet
        run: yarn build

      - name: Set bucket names
        id: setBucketNames
        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' }}
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
              echo "suite_bucket=suite.camino.foundation" >> $GITHUB_OUTPUT
              echo "wallet_bucket=suite-wallet.camino.foundation" >> $GITHUB_OUTPUT
              echo "explorer_bucket=suite-explorer.camino.foundation" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref_name }}" == "dev" ]]; then
              echo "suite_bucket=playground.suite.camino.foundation" >> $GITHUB_OUTPUT
              echo "wallet_bucket=playground.suite-wallet.camino.foundation" >> $GITHUB_OUTPUT
              echo "explorer_bucket=playground.suite-explorer.camino.foundation" >> $GITHUB_OUTPUT
          fi

      - name: 'gcloud authentication'
        id: 'auth'
        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' }}
        uses: 'google-github-actions/auth@v1'
        with:
            credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' }}
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: update suite bucket files
        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' }}
        working-directory: ./host
        run: gsutil rsync -R -d dist gs://${{ steps.setBucketNames.outputs.suite_bucket }}

      - name: update suite-explorer bucket files
        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' }}
        working-directory: ./blockexplorer
        run: gsutil rsync -R -d dist gs://${{ steps.setBucketNames.outputs.explorer_bucket }}

      - name: update suite-wallet bucket files
        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' }}
        working-directory: ./wallet
        run: gsutil rsync -R -d dist gs://${{ steps.setBucketNames.outputs.wallet_bucket }}
